/**
 * NOMBRE DE INTERFACE: EDITABLE
 * DESCRIPCION: INTERFACE QUE ALOJA METODOS DE EDICION DE IMAGENES
 *
 * METODOS
 * PUBLICOS:    FLIPH, PERMITE VOLTEAR HORIZONTALMENTE UNA IMAGEN.
 *              FLIPV, PERMITE VOLTEAR VERTICALMENTE UNA IMAGEN.
 *              CROP, PERMITE DESCARTAR DE LA IMAGEN TODOS AQUELLOS PIXELES QUE ESTEN FUERA DE UN RECTANGULO DETERMINADO.
 *              ROTATE90, PERMITE GIRAR EN ANGULO RECTO EN SENTIDO ANTIHORARIO UNA IMAGEN.
 *
 *
 * RELACIONES:  DE IMPLEMENTACION CON CLASE IMAGE
 */
public interface Editable_19273899_RojasTorrealba {
    public void flipH();

    public void flipV();

    public void crop(Integer x1, Integer y1, Integer x2, Integer y2);

    public void rotate90();
}
